### ISSUE TITLE
azure-arm-apimanagement module missing

### ISSUE THREAD

**Issue by JosephSemrai** [cloudlibz/nodecloud-web#21]
Upon trying to start this project with a manual installation of nodecloud-azure-plugin (https://github.com/cloudlibz/nodecloud-web/issues/18#issuecomment-566210092), the plugin makes use of a module that is not mentioned in its package.json.

Node Version: 12.3.0
This prevents the server from starting entirely unless the package is added and installed manually.
![image](https://user-images.githubusercontent.com/29003194/71503897-206b9f80-2845-11ea-945e-65f7fa92a4d9.png)

**Comment by amrita019** [comment]
Hey @JosephSemrai 

Thank you for bringing this to notice.
This might because the package is manually added to the project and linked. 
To fix this, can you try navigating to the root of the project via terminal and then hit
 
`cd server/node_modules/nodecloud-azure-plugin`
`npm i azure-arm-apimanagement`

And then try running the server again by npm start.
